'use client'

import React, { useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Smartphone, ChevronRight } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { OtpInput } from '@/components/ui/OtpInput'

interface TwoFactorFormProps {
    email: string;
    onBack: () => void;
    onSubmit: (e: React.FormEvent) => void;
    mfaCode: string;
    setMfaCode: (code: string) => void;
}

const TwoFactorForm: React.FC<TwoFactorFormProps> = ({
    email,
    onBack,
    onSubmit,
    mfaCode,
    setMfaCode,
}) => {
    const [mfaType, setMfaType] = useState<'totp' | 'email'>('totp');

    // Mask entered email address for privacy
    const maskEmail = (str: string) => {
        if (!str) return '***@company.com';
        const parts = str.split('@');
        if (parts.length < 2) return '***@company.com';
        const name = parts[0];
        const domain = parts[1];
        if (name.length <= 2) return `***@${domain}`;
        return `${name.slice(0, 1)}***${name.slice(-1)}@${domain}`;
    };

    return (
        <div className="space-y-6">
            {/* Back link */}
            <div>
                <button 
                    type="button"
                    onClick={onBack}
                    className="inline-flex items-center space-x-2 text-xs font-bold text-slate-500 hover:text-slate-350 transition-colors font-sans select-none"
                >
                    <ArrowLeft className="h-4 w-4" />
                    <span>Back to sign in</span>
                </button>
            </div>

            {/* Glowing Device Icon */}
            <div className="relative w-fit">
                <div className="absolute inset-0 rounded-2xl bg-primary-500/20 blur-[20px]"></div>
                <div className="relative w-12 h-12 rounded-2xl bg-primary-500/10 border border-primary-500/25 flex items-center justify-center text-primary-400">
                    <Smartphone className="h-5 w-5 text-primary-400" />
                </div>
            </div>

            {/* Header info */}
            <div className="space-y-2">
                <h1 className="font-satoshi font-black text-3xl text-white tracking-tight">
                    Two-factor authentication
                </h1>
                <p className="text-slate-400 text-sm font-sans leading-relaxed">
                    Your account is protected by 2FA. Enter the code from your authenticator app or email.
                </p>
            </div>

            {/* Pill switch switcher */}
            <div className="bg-[#0C1224]/50 border border-white/5 p-1 rounded-xl flex w-full select-none">
                <button
                    type="button"
                    onClick={() => {
                        setMfaType('totp');
                        setMfaCode('');
                    }}
                    className={`flex-grow py-2 text-xs font-bold rounded-lg transition-all ${
                        mfaType === 'totp' 
                            ? 'bg-primary-500 text-white shadow' 
                            : 'text-slate-500 hover:text-slate-350'
                    }`}
                >
                    Authenticator App
                </button>
                <button
                    type="button"
                    onClick={() => {
                        setMfaType('email');
                        setMfaCode('');
                    }}
                    className={`flex-grow py-2 text-xs font-bold rounded-lg transition-all ${
                        mfaType === 'email' 
                            ? 'bg-primary-500 text-white shadow' 
                            : 'text-slate-500 hover:text-slate-350'
                    }`}
                >
                    Email Code
                </button>
            </div>

            {/* MFA contextual description banner */}
            <div className="bg-[#0C1224]/40 border border-white/5 rounded-2xl p-5 select-none font-sans text-xs">
                {mfaType === 'totp' ? (
                    <span className="text-slate-355 leading-relaxed font-semibold">
                        Enter the 6-digit verification code generated by your authenticator app.
                    </span>
                ) : (
                    <span className="text-slate-355 leading-relaxed font-semibold">
                        A 6-digit code has been sent to your registered email address ending in{' '}
                        <strong className="text-white font-bold font-mono">{maskEmail(email)}</strong>
                    </span>
                )}
            </div>

            {/* Inputs Form */}
            <form onSubmit={onSubmit} className="space-y-6">
                <div className="space-y-2 text-left">
                    <label className="text-xs font-bold text-slate-500 tracking-wide block select-none">
                        Enter 6-digit code
                    </label>
                    <div className="flex justify-center max-w-[340px] py-1 select-none">
                        <OtpInput 
                            value={mfaCode}
                            onChange={setMfaCode}
                            length={6}
                        />
                    </div>
                </div>

                {/* CTA button */}
                <Button
                    type="submit"
                    variant="primary"
                    disabled={mfaCode.length !== 6}
                    className="w-full rounded-full h-[52px] font-semibold text-base shadow-lg shadow-primary-500/10"
                >
                    Verify & sign in
                </Button>
            </form>

            {/* Backup code / Support links */}
            <div className="space-y-4 select-none">
                <div className="text-center">
                    <button 
                        type="button"
                        className="inline-flex items-center text-xs font-bold text-primary-400 hover:underline"
                    >
                        <span>Use a backup code</span>
                        <ChevronRight className="h-3.5 w-3.5 ml-0.5" />
                    </button>
                </div>
                <div className="text-center text-[10px] text-slate-500 font-bold tracking-wide uppercase pt-2 border-t border-white/5">
                    Lost access to your 2FA device?{' '}
                    <Link href="/support" className="text-[#38BDF8] hover:underline">
                        Contact support
                    </Link>
                </div>
            </div>
        </div>
    )
}

export default TwoFactorForm
